/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.java.apps.frame;

import com.java.apps.pojo.LoginData;
import com.java.apps.user.panel.CreditCardPanel;
import com.java.apps.user.panel.MemberPanel;
import com.java.apps.user.panel.PaymentPanel;
import com.java.apps.user.panel.PaymentPanel;
import com.java.apps.user.panel.TransactionPanel;
import com.java.apps.user.panel.newTrasactionPanel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ultimate
 */
public class UserFrame extends javax.swing.JFrame {
    
    private MemberPanel member_panel;
    private CreditCardPanel credit_card_panel;
    private TransactionPanel transaction_panel;
    private newTrasactionPanel new_transaction_panel;
    private PaymentPanel payment_panel;
    

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
        
        lbl_username.setText(LoginData.username);
        lbl_login_time_value.setText(LoginData.login_time);
        
        // Register Panel //
        registerMemberPanel();
    }
    
    private void registerMemberPanel(){
        jPanel1.removeAll();
        member_panel = new MemberPanel();
        member_panel.setBounds(0, 0, 1280, 790);
        jPanel1.add(member_panel);                    
        setVisible(true);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }
    
    private void registerCardPanel(){
        jPanel1.removeAll();
        credit_card_panel = new CreditCardPanel();
        credit_card_panel.setBounds(0, 0, 1280, 640);
        jPanel1.add(credit_card_panel);                    
        setVisible(true);
        jPanel1.repaint();
        jPanel1.revalidate();         
    }
    
    private void registerTransactionPanel(){
        jPanel1.removeAll();
        transaction_panel = new TransactionPanel();
        transaction_panel.setBounds(0, 0, 1280, 640);
        jPanel1.add(transaction_panel);                    
        setVisible(true);
        jPanel1.repaint();
        jPanel1.revalidate();   
    }
    
    private void registerNewTransactionPanel(){
        jPanel1.removeAll();
        new_transaction_panel = new newTrasactionPanel();
        new_transaction_panel.setBounds(0, 0, 1280, 640);
        jPanel1.add(new_transaction_panel);                    
        setVisible(true);
        jPanel1.repaint();
        jPanel1.revalidate();   
    }
    
    private void registerPaymentPanel(){
        jPanel1.removeAll();
        payment_panel = new PaymentPanel();
        payment_panel.setBounds(0, 0, 1280, 640);
        jPanel1.add(payment_panel);                    
        setVisible(true);
        jPanel1.repaint();
        jPanel1.revalidate();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar3 = new javax.swing.JToolBar();
        btn_member = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_credit_card = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_transaksi = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_payment = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        lbl_user_login = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        lbl_login_time = new javax.swing.JLabel();
        lbl_login_time_value = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_file = new javax.swing.JMenu();
        mn_logout = new javax.swing.JMenuItem();
        mn_exit = new javax.swing.JMenuItem();
        mn_help = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jToolBar3.setRollover(true);

        btn_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_member_small.png"))); // NOI18N
        btn_member.setText("Member");
        btn_member.setFocusable(false);
        btn_member.setIconTextGap(9);
        btn_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_member);
        jToolBar3.add(jSeparator1);

        btn_credit_card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_credit_card_small.png"))); // NOI18N
        btn_credit_card.setText("Credit Card");
        btn_credit_card.setFocusable(false);
        btn_credit_card.setIconTextGap(9);
        btn_credit_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_credit_cardActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_credit_card);
        jToolBar3.add(jSeparator2);

        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_transaction_small.png"))); // NOI18N
        btn_transaksi.setText("Transaction");
        btn_transaksi.setFocusable(false);
        btn_transaksi.setIconTextGap(9);
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_transaksi);
        jToolBar3.add(jSeparator3);

        btn_payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_payment_small.png"))); // NOI18N
        btn_payment.setText("Payment");
        btn_payment.setFocusable(false);
        btn_payment.setIconTextGap(9);
        btn_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paymentActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_payment);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lbl_user_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_user_small1.png"))); // NOI18N
        lbl_user_login.setText("User Login : ");
        jToolBar1.add(lbl_user_login);

        lbl_username.setText("jLabel1");
        jToolBar1.add(lbl_username);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator4);

        lbl_login_time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_login_time_small.png"))); // NOI18N
        lbl_login_time.setText("Login Time : ");
        jToolBar1.add(lbl_login_time);

        lbl_login_time_value.setText("jLabel1");
        jToolBar1.add(lbl_login_time_value);

        mn_file.setText("File");

        mn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_exit_menu.png"))); // NOI18N
        mn_logout.setText("Logout");
        mn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_logoutActionPerformed(evt);
            }
        });
        mn_file.add(mn_logout);

        mn_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_exit_menu1.png"))); // NOI18N
        mn_exit.setText("Exit");
        mn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_exitActionPerformed(evt);
            }
        });
        mn_file.add(mn_exit);

        jMenuBar1.add(mn_file);

        mn_help.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/apps/resources/icon_about_menu.png"))); // NOI18N
        jMenuItem2.setText("About");
        mn_help.add(jMenuItem2);

        jMenuBar1.add(mn_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_exitActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, "Exit Application ?", "Exit Application", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mn_exitActionPerformed

    private void btn_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberActionPerformed
        registerMemberPanel();
    }//GEN-LAST:event_btn_memberActionPerformed

    private void mn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_logoutActionPerformed
        LoginFrame loginfrm = new LoginFrame();
        loginfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        loginfrm.setLocationRelativeTo(null);
        loginfrm.setVisible(true);    
        loginfrm.pack();                    
        dispose();
    }//GEN-LAST:event_mn_logoutActionPerformed

    private void btn_credit_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_credit_cardActionPerformed
        registerCardPanel();
    }//GEN-LAST:event_btn_credit_cardActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        //registerTransactionPanel();
        registerNewTransactionPanel();
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paymentActionPerformed
        registerPaymentPanel();
    }//GEN-LAST:event_btn_paymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_credit_card;
    private javax.swing.JButton btn_member;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lbl_login_time;
    private javax.swing.JLabel lbl_login_time_value;
    private javax.swing.JLabel lbl_user_login;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JMenuItem mn_exit;
    private javax.swing.JMenu mn_file;
    private javax.swing.JMenu mn_help;
    private javax.swing.JMenuItem mn_logout;
    // End of variables declaration//GEN-END:variables
}
