/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.java.apps.user.panel;

import com.java.apps.database.ConnectSQLLite;
import com.java.apps.pojo.BankItems;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ultimate
 */
public class CreditCardPanel extends javax.swing.JPanel {
    
    DefaultTableModel card_data_model;
    DefaultListModel bank_issuer_list = new DefaultListModel();

    /**
     * Creates new form CreditCardPanel
     */
    public CreditCardPanel() {
        initComponents();
                                                
        // Reload List //
        ReloadList();
    }
    
    private void ReloadList(){
        ConnectSQLLite sql_connect = new ConnectSQLLite();
        ArrayList<BankItems> bank_items = sql_connect.getBankData();
        
        for(BankItems item : bank_items){
            bank_issuer_list.addElement(item.bank_name);
        }
        
        list_bank_issuer.setModel(bank_issuer_list);
    }
    
    private void ReloadTable(int bank_id){
        card_data_model = new DefaultTableModel(){
            Class[] types = new Class[]{                
                java.lang.Integer.class, 
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class,
                java.lang.String.class                
            };    
                
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
               
        card_data_model.addColumn("Id");
        card_data_model.addColumn("Card Name");
        card_data_model.addColumn("Card Type");
        card_data_model.addColumn("Bank Issuer");
        card_data_model.addColumn("Holder");
                
        tbl_card.setModel(card_data_model);
        tbl_card.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                
        tbl_card.getColumnModel().getColumn(0).setPreferredWidth(50);   // card id //
        tbl_card.getColumnModel().getColumn(1).setPreferredWidth(180);  // card name //
        tbl_card.getColumnModel().getColumn(2).setPreferredWidth(150);  // card type //
        tbl_card.getColumnModel().getColumn(3).setPreferredWidth(200);  // bank issuer //
        tbl_card.getColumnModel().getColumn(4).setPreferredWidth(150);  // holder //
        
        tbl_card.setColumnSelectionAllowed(false);
        tbl_card.setRowSelectionAllowed(true);
        tbl_card.setSelectionBackground(Color.blue);
        ListSelectionModel rowSelectionModel = tbl_card.getSelectionModel();       
        rowSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        ConnectSQLLite sql_connection = new ConnectSQLLite();
        ArrayList<BankItems> bank_items = sql_connection.getCardDataByIssuer(bank_id + 1);
        
        for (BankItems item : bank_items){
            card_data_model.addRow(new Object[]{item.card_id, 
                                                item.card_name, 
                                                item.card_type_name,
                                                item.bank_name});
        }   
        
        rowSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                Object[] rowData = new Object[tbl_card.getColumnCount()];  
                for(int i = 0; i < tbl_card.getColumnCount(); i++) {  
                        rowData[i] = tbl_card.getValueAt(0, i) == null ? " " : tbl_card.getValueAt(0, i);  
                }  
                
                int card_id = Integer.parseInt(rowData[0].toString());                                                                                                   
            }
        });                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_bank_issuer = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_card = new javax.swing.JTable();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Card data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank issuer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        list_bank_issuer.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_bank_issuerValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(list_bank_issuer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Card data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        tbl_card.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_card);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void list_bank_issuerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_bank_issuerValueChanged
        String bank_issuer = list_bank_issuer.getSelectedValue().toString();
        int index = list_bank_issuer.getSelectedIndex();
        //JOptionPane.showMessageDialog(null, "Bank name : " + bank_issuer + " index : " + index); 
        ReloadTable(index);
    }//GEN-LAST:event_list_bank_issuerValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList list_bank_issuer;
    private javax.swing.JTable tbl_card;
    // End of variables declaration//GEN-END:variables
}
